version: '3'
services:
  web:
    image: ubuntu:20.04
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/bbs.conf:/etc/nginx/conf.d/bbs.conf
      - .:/app
    ports:
      - "3006:3006"
    command: sh -c "service php8.0-fpm start && nginx -g 'daemon off;'"
